language: haskell
ghc: '7.10.3'



before_install:
    - cabal sandbox init
    - cabal install happy
    - cabal install MissingH
    - cabal install directory
    - cabal install
    - cabal build
    - cabal configure
    - cabal build


