sudo: required
language: generic

services: 
    - docker

cache:
    directories:
        - ~/docker

before_script:
    - ls -lah ~/docker
    - if [[ -e ~/docker ]]; then ls ~/docker -lah; fi
    - if [[ -e ~/docker/haskell-go.tar ]]; then docker load -i ~/docker/haskell-go.tar; fi

script:
    - docker build --rm=false -t johan1a/haskell-go .

before_cache:
    - mkdir -p ~/docker; docker save johan1a/haskell-go > ~/docker/haskell-go.tar
    - ls ~/docker -lah
