sudo: required
language: generic

services: 
    - docker

dependencies:
    cache_directories:
        - "~/docker"

    override:
        - docker build --rm=false -t johan1a/haskell-go .

before_script:
    - ls ~/docker -lah
    - if [[ -e ~/docker/haskell-go.tar ]]; then docker load -i ~/docker/haskell-go.tar; fi

script:
    - docker build --rm=false -t johan1a/haskell-go .

after_script:
    - mkdir -p ~/docker; docker save johan1a/haskell-go > ~/docker/haskell-go.tar
    - ls ~/docker -lah
