language: haskell
ghc: 7.10

before_install:
    - "cabal sandbox init"
    - "cabal install happy"
    - "cabal install alex"
    - "cabal install MissingH"
    - "cabal install directory"
    - "cabal install"
    - "cabal build"
    - "cabal configure"
    - "cabal build"
    - "cabal insstall --enable-tests --only-dependencies"
